### ISSUE TITLE
Direct Discussion

### ISSUE THREAD

**Issue by chazo1994** [dathudeptrai/FastSpeech2#1]
You are did great work with TensorflowTTS, and may this project. I read fastspeech2 paper, fastspeech2s has a slight improvement in performance compared to fastspeech, but it's still worth a try. 
I'm live in Hanoi, hopefully when you come to Hanoi, we can have a coffee.

**Comment by dathudeptrai** [comment]
@chazo1994 :))) thanks. This repo is just a trick to let people search fastspeech2 can know TensorflowTTS :)). Let connect my linkedin if you want discussion more :))
